"use strict";
exports.__esModule = true;
var inheritance_1 = require("./inheritance");
// console.log('Hello from ts');
var myString;
var myNum;
var myBool;
var myVar;
// let strArr: string[];
// let numArr: number[];
// let boolArr: boolean[];
var strArr;
var numArr;
var boolArr;
var strNumTuple;
myString = 'hello world';
myNum = 33;
myBool = false;
myVar = true;
strArr = ['Hello', 'world'];
numArr = [1, 2, 3];
boolArr = [true, false, true];
strNumTuple = ['string1', 0];
var myVoid1 = null; //Can be-> let myVoid1: null = null;
var myVoid2 = undefined; //Can be-> let myVoid2: undefined = undefined;
console.log('myString =' + myString);
console.log('myNum =' + myNum);
console.log('myBool =' + myBool);
console.log('myVar =' + myVar);
console.log('strArr =' + strArr);
console.log('numArr =' + numArr);
console.log('myVar =' + myVar);
console.log('strNumTuple =' + strNumTuple);
console.log('myVoid1 =' + myVoid1);
console.log('myVoid2 =' + myVoid2);
var sam = new inheritance_1.Snake("Sammy the Python");
var tom = new inheritance_1.Horse("Tommy the Palomino");
sam.move();
tom.move(34);
